{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "thingsboard-ce.namespace" . }}
  labels:
    {{- include "thingsboard-ce.labels" . | nindent 4 }}
  {{- with .Values.namespace.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
