apiVersion: v1
kind: Service
metadata:
  name: {{ include "thingsboard-ce.fullname" . }}
  namespace: {{ include "thingsboard-ce.namespace" . }}
  labels:
    {{- include "thingsboard-ce.componentLabels" (dict "component" "core" "root" .) | nindent 4 }}
  annotations:
    {{- if .Values.service.annotations }}
    {{- toYaml .Values.service.annotations | nindent 4 }}
    {{- end }}
    {{- if eq .Values.service.type "LoadBalancer" }}
    {{- include "thingsboard-ce.loadBalancerAnnotations" . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- range .Values.service.loadBalancerSourceRanges }}
    - {{ . | quote }}
    {{- end }}
  {{- end }}
  {{- if and (eq .Values.service.type "ClusterIP") .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  {{- if .Values.service.externalIPs }}
  externalIPs:
    {{- range .Values.service.externalIPs }}
    - {{ . | quote }}
    {{- end }}
  {{- end }}
  {{- if .Values.service.sessionAffinity }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  {{- end }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) .Values.service.httpNodePort }}
      nodePort: {{ .Values.service.httpNodePort }}
      {{- end }}
    {{- if include "thingsboard-ce.isMonolith" . }}
    - port: {{ .Values.service.mqttPort }}
      targetPort: mqtt
      protocol: TCP
      name: mqtt
      {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) .Values.service.mqttNodePort }}
      nodePort: {{ .Values.service.mqttNodePort }}
      {{- end }}
    - port: {{ .Values.service.coapPort }}
      targetPort: coap
      protocol: UDP
      name: coap
      {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) .Values.service.coapNodePort }}
      nodePort: {{ .Values.service.coapNodePort }}
      {{- end }}
    {{- end }}
  selector:
    {{- include "thingsboard-ce.componentSelectorLabels" (dict "component" "core" "root" .) | nindent 4 }}
